### ISSUE TITLE
Add preset package manifest

### ISSUE THREAD

**Issue by sushichan044** [sushichan044/ajisai#29]
Like this
```toml
[package]
name = "my-ai-presets"

[[package.presets]]
name = "my-ai-presets-example1"
rules = ["rules/example1/rule1.md", "rules/example1/rule2.md"]
prompts = ["prompts/example1/prompt1.md", "prompts/example1/prompt2.md"]

[[package.presets]]
name = "my-ai-presets-example2"
rules = ["rules/example2/rule1.md", "rules/example2/rule2.md"]
prompts = ["prompts/example2/prompt1.md", "prompts/example2/prompt2.md"]

[sources.local_rules]
type = "local"
path = "./.ai"

[sources.my_ai_presets_example1]
type = "git"
repository = "https://github.com/sushichan044/ai-presets.git"

[targets.cursor]
enabled = true

[targets.github-copilot]
enabled = true

[targets.windsurf]
enabled = true
```
