### ISSUE TITLE
nil pointer exception occurs when set partial integrations settings

### ISSUE THREAD

**Issue by sushichan044** [sushichan044/ajisai#48]
```yaml
workspace:
  imports:
    rt-docs:
      type: git
      repository: https://github.com/heyinc/rt-docs.git
      include:
      - rails-style-guide
      - adr

  integrations:
    cursor:
      enabled: true
    github-copilot:
      enabled: true
```
Windsurf の設定を書いていない場合 false に fallback してほしいが、nil pointer exception になる
